/*
 * libfeedback
 * Copyright (c) 2012 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include <stdio.h>

const char *str_type[] =
{
	"FEEDBACK_TYPE_NONE",
	"FEEDBACK_TYPE_SOUND",
	"FEEDBACK_TYPE_VIBRATION",
	"FEEDBACK_TYPE_END",
};

const char *str_pattern[] =
{
	"FEEDBACK_PATTERN_TAP",
	"FEEDBACK_PATTERN_SIP",
	"FEEDBACK_PATTERN_SIP_BACKSPACE",
	"FEEDBACK_PATTERN_MAX_CHARACTER",
	"FEEDBACK_PATTERN_KEY0",
	"FEEDBACK_PATTERN_KEY1",
	"FEEDBACK_PATTERN_KEY2",
	"FEEDBACK_PATTERN_KEY3",
	"FEEDBACK_PATTERN_KEY4",
	"FEEDBACK_PATTERN_KEY5",
	"FEEDBACK_PATTERN_KEY6",
	"FEEDBACK_PATTERN_KEY7",
	"FEEDBACK_PATTERN_KEY8",
	"FEEDBACK_PATTERN_KEY9",
	"FEEDBACK_PATTERN_KEY_STAR",
	"FEEDBACK_PATTERN_KEY_SHARP",
	"FEEDBACK_PATTERN_HOLD",
	"FEEDBACK_PATTERN_MULTI_TAP",
	"FEEDBACK_PATTERN_HW_TAP",
	"FEEDBACK_PATTERN_HW_HOLD",
	"FEEDBACK_PATTERN_MESSAGE",
	"FEEDBACK_PATTERN_MESSAGE_ON_CALL",
	"FEEDBACK_PATTERN_EMAIL",
	"FEEDBACK_PATTERN_EMAIL_ON_CALL",
	"FEEDBACK_PATTERN_WAKEUP",
	"FEEDBACK_PATTERN_WAKEUP_ON_CALL",
	"FEEDBACK_PATTERN_SCHEDULE",
	"FEEDBACK_PATTERN_SCHEDULE_ON_CALL",
	"FEEDBACK_PATTERN_TIMER",
	"FEEDBACK_PATTERN_TIMER_ON_CALL",
	"FEEDBACK_PATTERN_GENERAL",
	"FEEDBACK_PATTERN_GENERAL_ON_CALL",
	"FEEDBACK_PATTERN_POWERON",
	"FEEDBACK_PATTERN_POWEROFF",
	"FEEDBACK_PATTERN_CHARGERCONN",
	"FEEDBACK_PATTERN_CHARGERCONN_ON_CALL",
	"FEEDBACK_PATTERN_FULLCHARGED",
	"FEEDBACK_PATTERN_FULLCHARGED_ON_CALL",
	"FEEDBACK_PATTERN_LOWBATT",
	"FEEDBACK_PATTERN_LOWBATT_ON_CALL",
	"FEEDBACK_PATTERN_LOCK",
	"FEEDBACK_PATTERN_UNLOCK",
	"FEEDBACK_PATTERN_CALLCONNECT",
	"FEEDBACK_PATTERN_DISCALLCONNECT",
	"FEEDBACK_PATTERN_MINUTEMINDER",
	"FEEDBACK_PATTERN_VIBRATION",
	"FEEDBACK_PATTERN_SHUTTER",
	"FEEDBACK_PATTERN_LIST_REORDER",
	"FEEDBACK_PATTERN_SLIDER_SWEEP",
	"FEEDBACK_PATTERN_VOLUME_KEY",
};
